swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Corporate Treasury'
 description: 'Description'
host: virtserver.swaggerhub.com
basePath: /BIAN/sd-corporate-treasury/1.0.0
schemes:
 - https
paths:
  /corporate-treasury/corporate-treasury-management-plan/initiation:
    post:
      tags:
      - initiate
      operationId: initiateCorporateTreasuryManagementPlan
      summary: InCR Initiate a corporate treasury plan
      description: InCR Initiate a corporate treasury plan
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: CorporateTreasury Request Payload
        schema:
          $ref: '#/definitions/CRCorporateTreasuryInitiateInputModel'
      responses:
        201:
          description: Successful InCR Initiate a corporate treasury plan
          schema:
            $ref: '#/definitions/CRCorporateTreasuryInitiateOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/updation:
    put:
      tags:
      - update
      operationId: updateCorporateTreasuryManagementPlan
      summary: UpCR Update the corporate treasury plan
      description: UpCR Update the corporate treasury plan
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: CorporateTreasury Request Payload
        schema:
          $ref: '#/definitions/CRCorporateTreasuryUpdateInputModel'
      responses:
        200:
          description: Successful UpCR Update the corporate treasury plan
          schema:
            $ref: '#/definitions/CRCorporateTreasuryUpdateOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/liquidity/initiation:
    post:
      tags:
      - initiate
      operationId: initiateCorporateTreasuryPlanLiquidity
      summary: InBQ Initiate a Corporate Treasury Liquidity Analysis
      description: Information used to track and manage the bank's cashflow and liquidity requirements
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Liquidity Request Payload
        schema:
          $ref: '#/definitions/BQLiquidityInitiateInputModel'
      responses:
        201:
          description: Successful InBQ Initiate a Corporate Treasury Liquidity Analysis
          schema:
            $ref: '#/definitions/LiquidityInitiateOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/tacticalfunding/initiation:
    post:
      tags:
      - initiate
      operationId: initiateCorporateTreasuryTacticalFunding
      summary: Initiate tactical funding details record
      description: Information used to determine and resolve short term funding requirements
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: TacticalFunding Request Payload
        schema:
          $ref: '#/definitions/BQTacticalFundingInitiateInputModel'
      responses:
        201:
          description: Successful Initiate tactical funding details record
          schema:
            $ref: '#/definitions/TacticalFundingInitiateOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/strategicfunding/initiation:
    post:
      tags:
      - initiate
      operationId: initiateCorporateTreasuryStrategicFunding
      summary: InBQ Initiate a large strategic transaction
      description: Information used to determine and resolve long term funding requirements
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: StrategicFunding Request Payload
        schema:
          $ref: '#/definitions/BQStrategicFundingInitiateInputModel'
      responses:
        201:
          description: Successful InBQ Initiate a large strategic transaction
          schema:
            $ref: '#/definitions/StrategicFundingInitiateOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/securitization/initiation:
    post:
      tags:
      - initiate
      operationId: initiateCorporateTreasurySecuritizationTask
      summary: InBQ Initiate securitization tranche and task details record
      description: Information used to determine and initiate securitization of bank assets
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Securitization Request Payload
        schema:
          $ref: '#/definitions/BQSecuritizationInitiateInputModel'
      responses:
        201:
          description: Successful InBQ Initiate securitization tranche and task details record
          schema:
            $ref: '#/definitions/SecuritizationInitiateOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/securitization/{bq-reference-id}/updation:
    put:
      tags:
      - update
      operationId: updateCorporateTreasurySecuritizationTask
      summary: UpBQ Update securitization tranche and task details
      description: Information used to determine and initiate securitization of bank assets
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Securitization BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Securitization Request Payload
        schema:
          $ref: '#/definitions/BQSecuritizationUpdateInputModel'
      responses:
        200:
          description: Successful UpBQ Update securitization tranche and task details
          schema:
            $ref: '#/definitions/BQSecuritizationUpdateOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/bankrates/initiation:
    post:
      tags:
      - initiate
      operationId: initiateCorporateTreasurySecuritizationTask
      summary: InBQ Initiate bank rate table and details
      description: Handling of the definition of internal bank rates used across production
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: BankRates Request Payload
        schema:
          $ref: '#/definitions/BQBankRatesInitiateInputModel'
      responses:
        201:
          description: Successful InBQ Initiate bank rate table and details
          schema:
            $ref: '#/definitions/BankRatesInitiateOutputModel'
  /corporate-treasury/corporate-treasury-management-plan:
    get:
      tags:
      - retrieve
      operationId: RetrieveCorporateTreasuryReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- 
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /corporate-treasury/corporate-treasury-management-plan/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCorporateTreasuryBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Liquidity',  'TacticalFunding',  'StrategicFunding',  'Securitization',  'BankRates', ]
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCorporateTreasuryBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 'BQ1'
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['BQID1', 'BQID2']
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCorporateTreasury
      summary: Retrieve a Corporate Treasury Record
      description: Retrieve a Corporate Treasury Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Corporate Treasury Request Payload
        schema:
          $ref: '#/definitions/CRCorporateTreasuryRetrieveInputModel'
      responses:
        200:
          description: Successfully Retrieved Corporate Treasury Report
          schema:
            $ref: '#/definitions/CRCorporateTreasuryRetrieveOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/liquidity/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCorporateTreasuryLiquidity
      summary: Retrieve a Corporate Treasury Liquidity Record
      description: Retrieve a Corporate Treasury Liquidity Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Liquidity BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Corporate Treasury Liquidity Request Payload
        schema:
          $ref: '#/definitions/BQLiquidityRetrieveInputModel'
      responses:
        200:
          description: Successfully Retrieved Corporate Treasury Liquidity Report
          schema:
            $ref: '#/definitions/BQLiquidityRetrieveOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/tacticalfunding/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCorporateTreasuryTacticalFunding
      summary: Retrieve a Corporate Treasury TacticalFunding Record
      description: Retrieve a Corporate Treasury TacticalFunding Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: TacticalFunding BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Corporate Treasury TacticalFunding Request Payload
        schema:
          $ref: '#/definitions/BQTacticalFundingRetrieveInputModel'
      responses:
        200:
          description: Successfully Retrieved Corporate Treasury TacticalFunding Report
          schema:
            $ref: '#/definitions/BQTacticalFundingRetrieveOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/strategicfunding/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCorporateTreasuryStrategicFunding
      summary: Retrieve a Corporate Treasury StrategicFunding Record
      description: Retrieve a Corporate Treasury StrategicFunding Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: StrategicFunding BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Corporate Treasury StrategicFunding Request Payload
        schema:
          $ref: '#/definitions/BQStrategicFundingRetrieveInputModel'
      responses:
        200:
          description: Successfully Retrieved Corporate Treasury StrategicFunding Report
          schema:
            $ref: '#/definitions/BQStrategicFundingRetrieveOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/securitization/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCorporateTreasurySecuritization
      summary: Retrieve a Corporate Treasury Securitization Record
      description: Retrieve a Corporate Treasury Securitization Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Securitization BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Corporate Treasury Securitization Request Payload
        schema:
          $ref: '#/definitions/BQSecuritizationRetrieveInputModel'
      responses:
        200:
          description: Successfully Retrieved Corporate Treasury Securitization Report
          schema:
            $ref: '#/definitions/BQSecuritizationRetrieveOutputModel'
  /corporate-treasury/corporate-treasury-management-plan/{cr-reference-id}/bankrates/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCorporateTreasuryBankRates
      summary: Retrieve a Corporate Treasury BankRates Record
      description: Retrieve a Corporate Treasury BankRates Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Corporate Treasury Management Plan Instance
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: BankRates BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Corporate Treasury BankRates Request Payload
        schema:
          $ref: '#/definitions/BQBankRatesRetrieveInputModel'
      responses:
        200:
          description: Successfully Retrieved Corporate Treasury BankRates Report
          schema:
            $ref: '#/definitions/BQBankRatesRetrieveOutputModel'
