swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Current Account'
 description: 'Description'
host: virtserver.swaggerhub.com
basePath: /BIAN/sd-current-account/1.0.0
schemes:
 - https
paths:
  /current-account/current-account-fulfullment-arrangement/initiation:
    post:
      tags:
      - initiate
      operationId: initiateCurrentAccountFulfillmentArrangement
      summary: Initiate/set-up a new current account facility
      description: InCR Initiate A new Current Account
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: Currentaccount Request Payload
        schema:
          $ref: '#/definitions/InitiateInputModel'
      responses:
        201:
          description: Successful Initiate/set-up a new current account facility
          schema:
            $ref: '#/definitions/InitiateOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/updation:
    put:
      tags:
      - update
      operationId: updateCurrentAccountFulfillmentArrangement
      summary: Update reference details of an active current account arrangement
      description: Update  Update reference details of an in-force current account,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Currentaccount Request Payload
        schema:
          $ref: '#/definitions/UpdateInputModel'
      responses:
        200:
          description: Successful Update reference details of an active current account arrangement
          schema:
            $ref: '#/definitions/UpdateOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/recording:
    post:
      tags:
      - record
      operationId: recordCurrentAccountFulfillmentArrangement
      summary: Record activity/feedback against a current account arrangement
      description: Record  Record activity against an active current account,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Record Request Payload
        schema:
          $ref: '#/definitions/RecordInputModel'
      responses:
        201:
          description: Successful Record activity/feedback against a current account arrangement
          schema:
            $ref: '#/definitions/RecordOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/deposit/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeCurrentAccountFulfillmentArrangementDepositUpdate
      summary: Execute a deposit transaction against the account
      description: Execute  Execute an account deposit,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Deposit BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Deposit request payload
        schema:
          $ref: '#/definitions/ExecuteInputModel'
      responses:
        200:
          description: Successful Execute a deposit transaction against the account
          schema:
            $ref: '#/definitions/ExecuteOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/deposit/execution:
    post:
      tags:
      - execute
      operationId: executeCurrentAccountFulfillmentArrangementDepositCreate
      summary: Execute a deposit transaction against the account
      description: Execute  Execute an account deposit,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Deposit Request Payload
        schema:
          $ref: '#/definitions/ExecuteInputModel'
      responses:
        201:
          description: Successful Execute a deposit transaction against the account
          schema:
            $ref: '#/definitions/ExecuteOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/standingorder/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestCurrentAccountFulfillmentArrangementStandingOrderUpdate
      summary: Request the set-up/amendment of a standing order
      description: Request  Request set-up/update of a standing order,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Standingorder BQ Reference Id
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Standingorder request payload
        schema:
          $ref: '#/definitions/RequestInputModel'
      responses:
        200:
          description: Successful Request the set-up/amendment of a standing order
          schema:
            $ref: '#/definitions/RequestOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/standingorder/requisition:
    post:
      tags:
      - request
      operationId: requestCurrentAccountFulfillmentArrangementStandingOrderCreate
      summary: Request the set-up/amendment of a standing order
      description: Request  Request set-up/update of a standing order,
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Standingorder Request Payload
        schema:
          $ref: '#/definitions/RequestInputModel'
      responses:
        201:
          description: Successful Request the set-up/amendment of a standing order
          schema:
            $ref: '#/definitions/RequestOutputModel'
  /current-account/current-account-fulfullment-arrangement:
    get:
      tags:
      - retrieve
      operationId: RetrieveCurrentAccountReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- 
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /current-account/current-account-fulfullment-arrangement/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCurrentAccountBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Interest',  'Service-Fees',  'Account-Lien',  'Account-Sweep',  'Deposits-Withrawals',  'Payments',  'Issued-Inventory', ]
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveCurrentAccountBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 'BQ1'
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['BQID1', 'BQID2']
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCurrentAccount
      summary: Retrieve a Current Account Record
      description: Retrieve a Current Account Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Current Account Report
          schema:
            $ref: '#/definitions/CurrentAccountCurrentAccountOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/interest/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCurrentAccountInterest
      summary: Retrieve a Current Account Interest Record
      description: Retrieve a Current Account Interest Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Interest BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Current Account Interest Report
          schema:
            $ref: '#/definitions/CurrentAccountInterestOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/service-fees/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCurrentAccountService-Fees
      summary: Retrieve a Current Account Service-Fees Record
      description: Retrieve a Current Account Service-Fees Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Service-Fees BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Current Account Service-Fees Report
          schema:
            $ref: '#/definitions/CurrentAccountService-FeesOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/account-lien/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCurrentAccountAccount-Lien
      summary: Retrieve a Current Account Account-Lien Record
      description: Retrieve a Current Account Account-Lien Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Account-Lien BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Current Account Account-Lien Report
          schema:
            $ref: '#/definitions/CurrentAccountAccount-LienOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/account-sweep/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCurrentAccountAccount-Sweep
      summary: Retrieve a Current Account Account-Sweep Record
      description: Retrieve a Current Account Account-Sweep Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Account-Sweep BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Current Account Account-Sweep Report
          schema:
            $ref: '#/definitions/CurrentAccountAccount-SweepOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/deposits-withrawals/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCurrentAccountDeposits-Withrawals
      summary: Retrieve a Current Account Deposits-Withrawals Record
      description: Retrieve a Current Account Deposits-Withrawals Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Deposits-Withrawals BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Current Account Deposits-Withrawals Report
          schema:
            $ref: '#/definitions/CurrentAccountDeposits-WithrawalsOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/payments/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCurrentAccountPayments
      summary: Retrieve a Current Account Payments Record
      description: Retrieve a Current Account Payments Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Payments BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Current Account Payments Report
          schema:
            $ref: '#/definitions/CurrentAccountPaymentsOutputModel'
  /current-account/current-account-fulfullment-arrangement/{cr-reference-id}/issued-inventory/{bq-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveCurrentAccountIssued-Inventory
      summary: Retrieve a Current Account Issued-Inventory Record
      description: Retrieve a Current Account Issued-Inventory Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Product Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: Issued-Inventory BQ Reference Id
        required: true
        type: string
      responses:
        200:
          description: Successfully Retrieved Current Account Issued-Inventory Report
          schema:
            $ref: '#/definitions/CurrentAccountIssued-InventoryOutputModel'
