swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Guideline Compliance'
 description: >
host: virtserver.swaggerhub.com
basePath: /BIAN/sd-guideline-compliance/1.0.0
schemes:
 - https
paths:
  /guideline-compliance/activation:
    post:
      tags:
      - activate
      operationId: activateSDGuidelineCompliance
      summary: Reference to a service activation service call
      description: Reference to a service activation service call
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDGuidelineCompliance Request Payload
        schema:
          $ref: '#/definitions/SDGuidelineComplianceActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDGuidelineComplianceActivateOutputModel'
  /guideline-compliance/configure:
    put:
      tags:
      - configure
      operationId: configureSDGuidelineCompliance
      summary: Reference to a service configuration service call
      description: Reference to a service configuration service call
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDGuidelineCompliance Configure Request Payload
        schema:
          $ref: '#/definitions/SDGuidelineComplianceConfigureInputModel'
      responses:
        201:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDGuidelineComplianceConfigureOutputModel'
  /guideline-compliance/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDGuidelineCompliance
      summary: Reference to a feedback service call
      description: Reference to a feedback service call
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDGuidelineCompliance Feedback Request Payload
        schema:
          $ref: '#/definitions/SDGuidelineComplianceFeedbackInputModel'
      responses:
        201:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDGuidelineComplianceFeedbackOutputModel'
  /guideline-compliance/retrieve:
    get:
      tags:
      - retrieve
      operationId: retrieveSDGuidelineCompliance
      summary: Reference to a retrieve service call
      description: Reference to a retrieve service call
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDGuidelineCompliance Retrieve Request Payload
        schema:
          $ref: '#/definitions/SDGuidelineComplianceRetrieveInputModel'
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDGuidelineComplianceRetrieveOutputModel'
  /guideline-compliance/guideline-compliance-assessment/initiation:
    post:
      tags:
      - initiate
      operationId: initiateGuidelineComplianceAssessment
      summary: Initiate/set-up a new Guideline Compliance Assessment
      description: Start a guideline compliance evaluation assessment
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: GuidelineComplianceAssessment Request Payload
        schema:
          $ref: '#/definitions/CRGuidelineComplianceAssessmentInitiateInputModel'
      responses:
        201:
          description: Successful Initiate/set-up a new Guideline Compliance Assessment
          schema:
            $ref: '#/definitions/CRGuidelineComplianceAssessmentInitiateOutputModel'
  /guideline-compliance/guideline-compliance-assessment/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateGuidelineComplianceAssessment
      summary: Update reference details of an active Guideline Compliance Assessment
      description: Update submitted details or content for an on-going guideline compliance assessment
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Record|
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: GuidelineComplianceAssessment Request Payload
        schema:
          $ref: '#/definitions/CRGuidelineComplianceAssessmentUpdateInputModel'
      responses:
        200:
          description: Successful Update reference details of an active Guideline Compliance Assessment
          schema:
            $ref: '#/definitions/CRGuidelineComplianceAssessmentUpdateOutputModel'
  /guideline-compliance/guideline-compliance-assessment/{cr-reference-id}/exchange:
    put:
      tags:
      - exchange
      operationId: exchangeGuidelineComplianceAssessmentUpdate
      summary: Handle an external exchange (e.g. accept, reject, verify)
      description: Accept or reject a guideline compliance determination
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Record|
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: GuidelineComplianceAssessment Request Payload
        schema:
          $ref: '#/definitions/CRGuidelineComplianceAssessmentExchangeInputModel'
      responses:
        200:
          description: Successful Handle an external exchange (e.g. accept, reject, verify)
          schema:
            $ref: '#/definitions/CRGuidelineComplianceAssessmentExchangeOutputModel'
  /guideline-compliance/guideline-compliance-assessment/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestGuidelineComplianceAssessmentUpdate
      summary: Invoke a service request action against the Guideline Compliance Assessment instance
      description: Request a review or adjudication for a guideline assessment
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Record|
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: GuidelineComplianceAssessment Request Payload
        schema:
          $ref: '#/definitions/CRGuidelineComplianceAssessmentRequestInputModel'
      responses:
        200:
          description: Successful Invoke a service request action against the Guideline Compliance Assessment instance
          schema:
            $ref: '#/definitions/CRGuidelineComplianceAssessmentRequestOutputModel'
  /guideline-compliance/guideline-compliance-assessment:
    get:
      tags:
      - retrieve
      operationId: RetrieveGuidelineComplianceReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- GuidelineCompliance Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /guideline-compliance/guideline-compliance-assessment/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveGuidelineComplianceBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: []
  /guideline-compliance/guideline-compliance-assessment/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveGuidelineComplianceBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Record|
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-  Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ID1, ID2]
  /guideline-compliance/guideline-compliance-assessment/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveGuidelineCompliance
      summary: Retrieve a Guideline Compliance Record
      description: Retrieve a Guideline Compliance Record
      produces:
      - application/json
      parameters:
      - name: cr-reference-id
        in: path
        description: Guideline Compliance Assessment Instance Record|
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Guideline Compliance Request Payload
        schema:
          $ref: '#/definitions/CRGuidelineComplianceRetrieveInputModel'
      responses:
        200:
          description: Successfully Retrieved Guideline Compliance Report
          schema:
            $ref: '#/definitions/CRGuidelineComplianceRetrieveOutputModel'
