swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Product Matching'
 description: >

    ## Executive Summary:
    The Product Matching service domain matches available product and product combinations to a customer based on various factors. The factors include the type of product of interest, the context (e.g. customer request, relationship review, retention action, cross/up sell). The matching selection may also be influenced by broader bank priorities and policies that can change with prevailing business conditions.

    ## Example of Use:
    A corporate customer relationship manager provides general advice to a customer seeking to invest a short term cash excess. The manager provides customer details and required product features to enable product matching to suggest the most appropriate product

    ## Description:
    This function provides an interactive match of available products (and product combinations) to a customer based on customer type/characteristics, the context for the request and desired product/service features. The matching mechanism can prompt for additional details as may be necessary to select a product and/or confirm the eligibility of the customer. The facility can also consider broader factors such as business preferences/strategy and prevailing business/market conditions when selecting products. Product Matching references the Customer Product/Service Eligibility service domain where the customer's use and eligibility to the bank's full range of products and services is maintained in order to limit the matching to only those products for which the customer is entitled and not already using

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-product-matching/1.0.0
schemes:
 - https
paths:
  /product-matching/activation:
    post:
      tags:
      - activate
      operationId: activateSDProductMatching
      summary: Activate  a SDProductMatching servicing session
      description: Activate  a  SDProductMatching servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDProductMatching Request Payload
        schema:
          $ref: '#/definitions/SDProductMatchingActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDProductMatchingActivateOutputModel'
  /product-matching/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDProductMatching
      summary: Update an active SDProductMatching session configuration
      description: Update an active SDProductMatching session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDProductMatching Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDProductMatching Configure Request Payload
        schema:
          $ref: '#/definitions/SDProductMatchingConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDProductMatchingConfigureOutputModel'
  /product-matching/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDProductMatching
      summary: "Capturing feedback against the SDProductMatching service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDProductMatching service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDProductMatching Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDProductMatching Feedback Request Payload
        schema:
          $ref: '#/definitions/SDProductMatchingFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDProductMatchingFeedbackOutputModel'
  /product-matching/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDProductMatching
      summary: Analytical views maintained by the SDProductMatching service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDProductMatching service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDProductMatching Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDProductMatching Retrieve Request Payload
        schema:
          $ref: '#/definitions/SDProductMatchingRetrieveInputModel'
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDProductMatchingRetrieveOutputModel'
  /product-matching/{sd-reference-id}/product-customer-combination-analysis/evaluation:
    post:
      tags:
      - evaluate
      operationId: evaluateProductCustomerCombinationAnalysis
      summary: Details of a new ProductCustomerCombinationAnalysis instance
      description: Evaluate the best eligible product to suit a customer sales opportunity
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Matching Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: ProductCustomerCombinationAnalysis Request Payload
        schema:
          $ref: '#/definitions/CRProductCustomerCombinationAnalysisEvaluateInputModel'
      responses:
        201:
          description: Successful evaluation of new ProductCustomerCombinationAnalysis instance
          schema:
            $ref: '#/definitions/CRProductCustomerCombinationAnalysisEvaluateOutputModel'
  /product-matching/{sd-reference-id}/product-customer-combination-analysis/{cr-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateProductCustomerCombinationAnalysis
      summary: Update to any amendable fields of the ProductCustomerCombinationAnalysis instance
      description: Update details for an active evaluation
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Matching Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Customer Combination Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product Customer Combination Analysis Request Payload
        schema:
          $ref: '#/definitions/CRProductCustomerCombinationAnalysisUpdateInputModel'
      responses:
        200:
          description: Successfully Updated Product Customer Combination Analysis Instance
          schema:
            $ref: '#/definitions/CRProductCustomerCombinationAnalysisUpdateOutputModel'
  /product-matching/{sd-reference-id}/product-customer-combination-analysis/{cr-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeProductCustomerCombinationAnalysisUpdate
      summary: Invoke an automated execute action against the ProductCustomerCombinationAnalysis instance
      description: Execute an automated action against an evaluation (e.g. upload data)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Matching Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Customer Combination Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product Customer Combination Analysis Request Payload
        schema:
          $ref: '#/definitions/CRProductCustomerCombinationAnalysisExecuteInputModel'
      responses:
        200:
          description: Successful execution of Product Customer Combination Analysis Instance
          schema:
            $ref: '#/definitions/CRProductCustomerCombinationAnalysisExecuteOutputModel'
  /product-matching/{sd-reference-id}/product-customer-combination-analysis/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestProductCustomerCombinationAnalysisUpdate
      summary: Invoke a service request action against the ProductCustomerCombinationAnalysis instance
      description: Request manual intervention (e.g. request specialist support)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Matching Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Customer Combination Analysis Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Product Customer Combination Analysis Request Payload
        schema:
          $ref: '#/definitions/CRProductCustomerCombinationAnalysisRequestInputModel'
      responses:
        200:
          description: Successful requisition of Product Customer Combination Analysis Instance
          schema:
            $ref: '#/definitions/CRProductCustomerCombinationAnalysisRequestOutputModel'
  /product-matching/{sd-reference-id}/product-customer-combination-analysis/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveProductMatching
      summary: Invoke a reporting action to obtain a Product Customer Combination Analysis instance related report
      description: Retrieve details about a product matching analysis
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Matching Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Customer Combination Analysis Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRProductCustomerCombinationAnalysisRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Product Customer Combination Analysis Instance
          schema:
            $ref: '#/definitions/CRProductCustomerCombinationAnalysisRetrieveOutputModel'
  /product-matching/{sd-reference-id}/product-customer-combination-analysis:
    get:
      tags:
      - retrieve
      operationId: RetrieveProductMatchingReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Matching Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- ProductMatching Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /product-matching/product-customer-combination-analysis/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveProductMatchingBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: []
  /product-matching/{sd-reference-id}/product-customer-combination-analysis/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveProductMatchingBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Product Matching Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Product Customer Combination Analysis Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- 
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex-  Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ID1, ID2]
