swagger: '2.0'
info:
 version: '1.0.0'
 title: 'Service Domain - Regulatory Reporting'
 description: >

    ## Executive Summary:
    This service domain administers and orchestrates the tasks required to meet the bank's regulatory reporting obligations

    ## Example of Use:
    Trading activity is reported to the exchange to comply with regulatory reporting requirements

    ## Description:
    The service domain handles the bank's regulatory reporting obligations. This includes the consolidation and presentation of information in regulatory reports and disclosures and handling the response to regulatory requests for information as part of ongoing regulator relations. It also handles the scheduled consolidation, formatting and delivery of the range of compliance reports including 'on-line' trade reporting and after the event transaction analysis reporting

host: virtserver.swaggerhub.com
basePath: /BIAN/sd-regulatory-reporting/1.0.0
schemes:
 - https
paths:
  /regulatory-reporting/activation:
    post:
      tags:
      - activate
      operationId: activateSDRegulatoryReporting
      summary: Activate  a SDRegulatoryReporting servicing session
      description: Activate  a  SDRegulatoryReporting servicing session
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        required: true
        description: SDRegulatoryReporting Request Payload
        schema:
          $ref: '#/definitions/SDRegulatoryReportingActivateInputModel'
      responses:
        201:
          description: Successful Service Activation
          schema:
            $ref: '#/definitions/SDRegulatoryReportingActivateOutputModel'
  /regulatory-reporting/{sd-reference-id}/configuration:
    put:
      tags:
      - configure
      operationId: configureSDRegulatoryReporting
      summary: Update an active SDRegulatoryReporting session configuration
      description: Update an active SDRegulatoryReporting session configuration
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDRegulatoryReporting Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDRegulatoryReporting Configure Request Payload
        schema:
          $ref: '#/definitions/SDRegulatoryReportingConfigureInputModel'
      responses:
        200:
          description: Successful Service Configuration
          schema:
            $ref: '#/definitions/SDRegulatoryReportingConfigureOutputModel'
  /regulatory-reporting/{sd-reference-id}/feedback:
    put:
      tags:
      - feedback
      operationId: feedbackSDRegulatoryReporting
      summary: "Capturing feedback against the SDRegulatoryReporting service that can target different levels of detail: SD/CR/BQ"
      description:  "Capturing feedback against the SDRegulatoryReporting service that can target different levels of detail: SD/CR/BQ"
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDRegulatoryReporting Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDRegulatoryReporting Feedback Request Payload
        schema:
          $ref: '#/definitions/SDRegulatoryReportingFeedbackInputModel'
      responses:
        200:
          description: Successful Service Feedback
          schema:
            $ref: '#/definitions/SDRegulatoryReportingFeedbackOutputModel'
  /regulatory-reporting/{sd-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveSDRegulatoryReporting
      summary: Analytical views maintained by the SDRegulatoryReporting service center for management reporting and analysis purposes
      description: Analytical views maintained by the SDRegulatoryReporting service center for management reporting and analysis purposes
      produces:
      - application/json
      parameters:
      - in: path
        name: sd-reference-id
        required: true
        description: SDRegulatoryReporting Servicing Session Reference
        type: string
      - in: body
        name: body
        required: true
        description: SDRegulatoryReporting Retrieve Request Payload
        schema:
          $ref: '#/definitions/SDRegulatoryReportingRetrieveInputModel'
      responses:
        200:
          description: Successful Service Retrieve
          schema:
            $ref: '#/definitions/SDRegulatoryReportingRetrieveOutputModel'
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan/initiation:
    post:
      tags:
      - initiate
      operationId: initiateRegulatoryComplianceAdministrativePlan
      summary: Details of a new RegulatoryComplianceAdministrativePlan instance
      description: Start the IP service feed
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: RegulatoryComplianceAdministrativePlan Request Payload
        schema:
          $ref: '#/definitions/CRRegulatoryComplianceAdministrativePlanInitiateInputModel'
      responses:
        201:
          description: Successful initiation of new RegulatoryComplianceAdministrativePlan instance
          schema:
            $ref: '#/definitions/CRRegulatoryComplianceAdministrativePlanInitiateOutputModel'
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan/{cr-reference-id}/control:
    put:
      tags:
      - control
      operationId: controlRegulatoryComplianceAdministrativePlanUpdate
      summary: Request specific processing (e.g. suspend, skip, terminate)
      description: Reconfigure the existing feed make-up
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Regulatory Compliance Administrative Plan Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Regulatory Compliance Administrative Plan Request Payload
        schema:
          $ref: '#/definitions/CRRegulatoryComplianceAdministrativePlanControlInputModel'
      responses:
        200:
          description: Successful control of Regulatory Compliance Administrative Plan Instance
          schema:
            $ref: '#/definitions/CRRegulatoryComplianceAdministrativePlanControlOutputModel'
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan/{cr-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestRegulatoryComplianceAdministrativePlanUpdate
      summary: Invoke a service request action against the RegulatoryComplianceAdministrativePlan instance
      description: Request/change delivery of an allowed service feed (note service agreement/pricing handled elsewhere)
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Regulatory Compliance Administrative Plan Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: Regulatory Compliance Administrative Plan Request Payload
        schema:
          $ref: '#/definitions/CRRegulatoryComplianceAdministrativePlanRequestInputModel'
      responses:
        200:
          description: Successful requisition of Regulatory Compliance Administrative Plan Instance
          schema:
            $ref: '#/definitions/CRRegulatoryComplianceAdministrativePlanRequestOutputModel'
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan/{cr-reference-id}:
    get:
      tags:
      - retrieve
      operationId: retrieveRegulatoryReporting
      summary: Invoke a reporting action to obtain a Regulatory Compliance Administrative Plan instance related report
      description: Read details/reports about the IP service feed
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Regulatory Compliance Administrative Plan Instance Reference
        required: true
        type: string
      - in: query
        name: queryparams
        required: false
        description: Query params from schema '#/definitions/CRRegulatoryComplianceAdministrativePlanRetrieveInputModel'
        type: string
      responses:
        200:
          description: Successfully Retrieved Regulatory Compliance Administrative Plan Instance
          schema:
            $ref: '#/definitions/CRRegulatoryComplianceAdministrativePlanRetrieveOutputModel'
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan/{cr-reference-id}/serviceselection/{bq-reference-id}/requisition:
    put:
      tags:
      - request
      operationId: requestRegulatoryComplianceAdministrativePlanServiceSelectionUpdate
      summary: Invoke a service request action against the ServiceSelection instance
      description: Request changes to the feed service make-up
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Regulatory Compliance Administrative Plan Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: ServiceSelection Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: ServiceSelection request payload
        schema:
          $ref: '#/definitions/BQServiceSelectionRequestInputModel'
      responses:
        200:
          description: Successful requisition of ServiceSelection Instance Record
          schema:
            $ref: '#/definitions/BQServiceSelectionRequestOutputModel'
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan/{cr-reference-id}/informationimport/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeRegulatoryComplianceAdministrativePlanInformationImportUpdate
      summary: Invoke an automated execute action against the InformationImport instance
      description: Execute an information service import instruction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Regulatory Compliance Administrative Plan Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: InformationImport Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: InformationImport request payload
        schema:
          $ref: '#/definitions/BQInformationImportExecuteInputModel'
      responses:
        200:
          description: Successful execution of InformationImport Instance Record
          schema:
            $ref: '#/definitions/BQInformationImportExecuteOutputModel'
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan/{cr-reference-id}/informationexport/{bq-reference-id}/update:
    put:
      tags:
      - update
      operationId: updateRegulatoryComplianceAdministrativePlanInformationExport
      summary: Update to any amendable fields of the InformationExport instance
      description: Update/correct an information service exported message
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Regulatory Compliance Administrative Plan Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: InformationExport Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: InformationExport Request Payload
        schema:
          $ref: '#/definitions/BQInformationExportUpdateInputModel'
      responses:
        200:
          description: Successfully Updated InformationExport Instance
          schema:
            $ref: '#/definitions/BQInformationExportUpdateOutputModel'
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan/{cr-reference-id}/informationexport/{bq-reference-id}/execution:
    put:
      tags:
      - execute
      operationId: executeRegulatoryComplianceAdministrativePlanInformationExportUpdate
      summary: Invoke an automated execute action against the InformationExport instance
      description: Execute an information service export instruction
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Regulatory Compliance Administrative Plan Instance Reference
        required: true
        type: string
      - name: bq-reference-id
        in: path
        description: InformationExport Instance Reference
        required: true
        type: string
      - in: body
        name: body
        required: true
        description: InformationExport request payload
        schema:
          $ref: '#/definitions/BQInformationExportExecuteInputModel'
      responses:
        200:
          description: Successful execution of InformationExport Instance Record
          schema:
            $ref: '#/definitions/BQInformationExportExecuteOutputModel'
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan:
    get:
      tags:
      - retrieve
      operationId: RetrieveRegulatoryReportingReferenceIds
      summary: Retrieve CR Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- RegulatoryReporting Instance Status='active'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: ['ID726464', 'ID7264642']
  /regulatory-reporting/regulatory-compliance-administrative-plan/behavior-qualifiers/:
    get:
      tags:
      - retrieve
      operationId: RetrieveRegulatoryReportingBehaviorQualifiers
      summary: Retrieve BQ names
      produces:
      - application/json
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [ 'Consolidation',  'Authoring',  'Enquiries', ]
  /regulatory-reporting/{sd-reference-id}/regulatory-compliance-administrative-plan/{cr-reference-id}/{behavior-qualifier}/:
    get:
      tags:
      - retrieve
      operationId: RetrieveRegulatoryReportingBehaviorQualifierReferenceIds
      summary: Retrieve Behavior Qualifier Reference Ids
      produces:
      - application/json
      parameters:
      - name: sd-reference-id
        in: path
        description: Regulatory Reporting Servicing Session Reference
        required: true
        type: string
      - name: cr-reference-id
        in: path
        description: Regulatory Compliance Administrative Plan Instance Reference
        required: true
        type: string
      - name : behavior-qualifier
        in: path
        description: Behavior Qualifier Name. ex- Enquiries
        required: true
        type: string
      - name : collection-filter
        in: query
        description: Filter to refine the result set. ex- Enquiries Instance Status = 'pending'
        required: false
        type: string
      responses:
        200:
          description: Successful
          schema:
            type: array
            items:
              type: string
            example: [EnquiriesID1, EnquiriesID2]
